/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Andres
 */
public class JFGestion extends javax.swing.JFrame {

    /**
     * Creates new form JFGestion
     */
    public JFGestion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        JMRegistrar = new javax.swing.JMenuItem();
        JMConsultar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmCrearCuenta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_154-man-office-worker-2_3099407-2.png"))); // NOI18N
        jMenuCliente.setText("Clientes");

        JMRegistrar.setText("Registrar");
        JMRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMRegistrarActionPerformed(evt);
            }
        });
        jMenuCliente.add(JMRegistrar);

        JMConsultar.setText("Consultar-Modificar");
        JMConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMConsultarActionPerformed(evt);
            }
        });
        jMenuCliente.add(JMConsultar);

        jMenuBar2.add(jMenuCliente);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_Purse_669953.png"))); // NOI18N
        jMenu4.setText("Cuentas");

        jmCrearCuenta.setText("Crear Cuenta");
        jmCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearCuentaActionPerformed(evt);
            }
        });
        jMenu4.add(jmCrearCuenta);

        jMenuBar2.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_order-history_49596.png"))); // NOI18N
        jMenu1.setText("Transacciones");

        jMenuItem1.setText("Operaciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMRegistrarActionPerformed
        JDClientes obj = new JDClientes(this, true);
        
        JDClientes.btnEliminar.setEnabled(false);
        JDClientes.btnModificar.setEnabled(false);
        obj.setVisible(true);
    }//GEN-LAST:event_JMRegistrarActionPerformed

    private void JMConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMConsultarActionPerformed
        JDClientes obj = new JDClientes(this, true);
        
        JDClientes.btnEliminar.setEnabled(false);
        JDClientes.btnRegistrar.setEnabled(false);
        JDClientes.cbEstado.setEnabled(false);
        JDClientes.cbTipoCliente.setEnabled(false);
        JDClientes.txtApellido.setEnabled(false);
        JDClientes.txtNombre.setEnabled(false);
        JDClientes.txtTelefono.setEnabled(false);
        JDClientes.btnModificar.setEnabled(false);
        obj.setVisible(true);
    }//GEN-LAST:event_JMConsultarActionPerformed

    private void jmCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearCuentaActionPerformed
        JDCuenta obj = new JDCuenta(this, true);
        
        obj.setVisible(true);
    }//GEN-LAST:event_jmCrearCuentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDTransaccion obj = new JDTransaccion(this,true);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMConsultar;
    private javax.swing.JMenuItem JMRegistrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmCrearCuenta;
    // End of variables declaration//GEN-END:variables
}
